(()=>{const DATA=window.TOKYO_DATA;let tab='spots',area='전체',category='전체',query='';const $=s=>document.querySelector(s);const cards=$('#cards'),filters=$('#filters'),search=$('#searchInput');const titles={spots:['🗼 여행지 리스트','도쿄에서 많이 찾는 관광·산책·전망·쇼핑 명소'],restaurants:['🍜 맛집 리스트','라멘·돈카츠·초밥·카페 등 도쿄 인기 식사 후보']};const pageCopy={spots:['여행지 리스트','관광·산책·전망·쇼핑 중 원하는 테마를 고르고 지역까지 좁혀보세요.'],restaurants:['맛집 리스트','지역과 검색을 조합해 도쿄에서 먹고 싶은 메뉴를 빠르게 찾아보세요.']};const catIcon={'전체':'전체','관광':'🏯 관광','산책':'🚶 산책','전망':'🌆 전망','쇼핑':'🛍️ 쇼핑'};
function mapSrc(q){return 'https://www.google.com/maps?q='+encodeURIComponent(q)+'&output=embed'}
function googleUrl(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function current(){return DATA[tab]||[]}
function areas(){return ['전체',...new Set(current().map(x=>x.area))]}
function renderCategoryButtons(){const box=$('#spotCategoryBox');box.hidden=tab!=='spots';if(tab!=='spots')return;const cats=['전체','관광','산책','전망','쇼핑'];$('#spotCategories').innerHTML=cats.map(c=>{const count=c==='전체'?DATA.spots.length:DATA.spots.filter(x=>(x.categories||[]).includes(c)).length;return `<button class="category-btn ${c===category?'active':''}" data-category="${esc(c)}">${catIcon[c]} <span class="count">${count}</span></button>`}).join('');$('#spotCategories').querySelectorAll('.category-btn').forEach(b=>b.onclick=()=>{category=b.dataset.category;area='전체';renderCategoryButtons();renderFilters();renderCards()})}
function renderFilters(){filters.innerHTML=areas().map(a=>`<button class="filter ${a===area?'active':''}" data-area="${esc(a)}">${esc(a)}</button>`).join('');filters.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{area=b.dataset.area;renderFilters();renderCards()})}
function filtered(){const q=query.trim().toLowerCase();return current().filter(x=>(area==='전체'||x.area===area)&&(tab!=='spots'||category==='전체'||(x.categories||[]).includes(category))&&(!q||[x.name,x.area,x.desc,...(x.tags||[]),...(x.categories||[])].join(' ').toLowerCase().includes(q)))}
function renderCards(){const list=filtered();$('#empty').hidden=!!list.length;$('#resultMeta').textContent=`${list.length}개 장소 표시 중`;cards.innerHTML=list.map(x=>`<button class="place-card" data-name="${escAttr(x.name)}"><div class="card-row"><h3>${esc(x.name)}</h3><span class="area">${esc(x.area)}</span></div><p>${esc(x.desc)}</p><div class="tags">${tab==='spots'?(x.categories||[]).map(t=>`<span class="tag category-tag">${esc(t)}</span>`).join(''):''}${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="mini">${x.bestFor?'추천 시간 · '+esc(x.bestFor):''}${x.note?' · '+esc(x.note):''}</div></button>`).join('');cards.querySelectorAll('.place-card').forEach(btn=>btn.onclick=()=>select(current().find(x=>x.name===btn.dataset.name),btn));if(list.length){const btn=cards.querySelector('.place-card');select(list[0],btn)}}
function select(x,btn){if(!x)return;document.querySelectorAll('.place-card').forEach(c=>c.classList.remove('active'));if(btn)btn.classList.add('active');$('#selectedName').textContent=x.name;$('#selectedMeta').textContent=[x.area,...(x.categories||[]),...(x.tags||[])].join(' · ');$('#selectedDesc').textContent=x.desc;$('#selectedBest').textContent=x.bestFor?'추천 시간 · '+x.bestFor:'';const pri=$('#selectedPriority');pri.hidden=!x.priority;pri.textContent=x.priority||'';const note=$('#selectedNote');note.hidden=!x.note;note.textContent=x.note?'참고 · '+x.note:'';$('#mapFrame').src=mapSrc(x.query||x.name+' Tokyo Japan');$('#openGoogle').href=googleUrl(x.query||x.name+' Tokyo Japan');if(innerWidth<961) document.querySelector('.map-panel').scrollIntoView({behavior:'smooth',block:'start'})}
function switchTab(next){tab=next;area='전체';category='전체';query='';search.value='';document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#listTitle').textContent=titles[tab][0];$('#listSub').textContent=titles[tab][1];$('#pageTitle').textContent=pageCopy[tab][0];$('#pageSub').textContent=pageCopy[tab][1];renderCategoryButtons();renderFilters();renderCards()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(s){return esc(s)}
$('#spotCount').textContent=DATA.spots.length;$('#foodCount').textContent=DATA.restaurants.length;$('#summaryCount').textContent=DATA.spots.length+DATA.restaurants.length;document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));search.oninput=e=>{query=e.target.value;renderCards()};switchTab('spots');})();
