(()=>{
const DATA=window.TOKYO_DATA;
let tab='spots',area='전체',category='전체',query='',selectedName='';
const $=s=>document.querySelector(s), cards=$('#cards'),filters=$('#filters'),search=$('#searchInput');
const titles={spots:['🗼 여행지 리스트','도쿄에서 많이 찾는 관광·산책·전망·쇼핑 명소'],restaurants:['🍜 맛집 리스트','라멘·돈카츠·초밥·카페 등 도쿄 인기 식사 후보']};
const pageCopy={spots:['여행지 리스트','관광·산책·전망·쇼핑 중 원하는 테마를 고르고 지역까지 좁혀보세요.'],restaurants:['맛집 리스트','지역과 검색을 조합해 도쿄에서 먹고 싶은 메뉴를 빠르게 찾아보세요.']};
const catIcon={'전체':'전체','관광':'🏯 관광','산책':'🚶 산책','전망':'🌆 전망','쇼핑':'🛍️ 쇼핑'};
const classByCat={'관광':'tour','산책':'walk','전망':'view','쇼핑':'shop'};
let map=null, markerLayer=null, markerByName=new Map(), renderToken=0;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(s){return esc(s)}
function googleUrl(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function current(){return tab==='spots'?DATA.spots:DATA.restaurants}
function areas(){return ['전체',...new Set(current().map(x=>x.area))]}
function markerClass(x){return tab==='restaurants'?'food':(classByCat[(x.categories||[])[0]]||'tour')}
function filtered(){const q=query.trim().toLowerCase();return current().filter(x=>(area==='전체'||x.area===area)&&(tab!=='spots'||category==='전체'||(x.categories||[]).includes(category))&&(!q||[x.name,x.area,x.desc,...(x.tags||[]),...(x.categories||[])].join(' ').toLowerCase().includes(q)))}
function renderCategoryButtons(){const box=$('#spotCategoryBox');box.hidden=tab!=='spots';if(tab!=='spots')return;const cats=['전체','관광','산책','전망','쇼핑'];$('#spotCategories').innerHTML=cats.map(c=>{const count=c==='전체'?DATA.spots.length:DATA.spots.filter(x=>(x.categories||[]).includes(c)).length;return `<button class="category-btn ${c===category?'active':''}" data-category="${esc(c)}">${catIcon[c]} <span class="count">${count}</span></button>`}).join('');$('#spotCategories').querySelectorAll('.category-btn').forEach(b=>b.onclick=()=>{category=b.dataset.category;area='전체';renderCategoryButtons();renderFilters();renderCards()})}
function renderFilters(){filters.innerHTML=areas().map(a=>`<button class="filter ${a===area?'active':''}" data-area="${esc(a)}">${esc(a)}</button>`).join('');filters.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{area=b.dataset.area;renderFilters();renderCards()})}
function renderCards(){const list=filtered();$('#empty').hidden=!!list.length;$('#resultMeta').textContent=`${list.length}개 장소 표시 중 · 지도에도 동일하게 표시`;cards.innerHTML=list.map((x,i)=>`<button class="place-card" data-name="${escAttr(x.name)}"><span class="list-number ${markerClass(x)}">${i+1}</span><div class="card-row"><h3>${esc(x.name)}</h3><span class="area">${esc(x.area)}</span></div><p>${esc(x.desc)}</p><div class="tags">${tab==='spots'?(x.categories||[]).map(t=>`<span class="tag category-tag">${esc(t)}</span>`).join(''):''}${(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="mini">${x.bestFor?'추천 시간 · '+esc(x.bestFor):''}${x.note?' · '+esc(x.note):''}</div></button>`).join('');cards.querySelectorAll('.place-card').forEach(btn=>btn.onclick=()=>select(current().find(x=>x.name===btn.dataset.name),btn));updateMap(list);if(list.length){select(list[0],cards.querySelector('.place-card'),false)}else clearSelected()}
function clearSelected(){selectedName='';$('#selectedName').textContent='표시할 장소 없음';$('#selectedMeta').textContent='필터 조건을 변경해 주세요.';$('#selectedDesc').textContent='';$('#selectedBest').textContent='';$('#selectedPriority').hidden=true;$('#selectedNote').hidden=true;$('#openGoogle').removeAttribute('href')}
function select(x,btn,move=true){if(!x)return;selectedName=x.name;document.querySelectorAll('.place-card').forEach(c=>c.classList.remove('active'));if(btn)btn.classList.add('active');$('#selectedName').textContent=x.name;$('#selectedMeta').textContent=[x.area,...(x.categories||[]),...(x.tags||[])].join(' · ');$('#selectedDesc').textContent=x.desc;$('#selectedBest').textContent=x.bestFor?'추천 시간 · '+x.bestFor:'';const pri=$('#selectedPriority');pri.hidden=!x.priority;pri.textContent=x.priority||'';const note=$('#selectedNote');note.hidden=!x.note;note.textContent=x.note?'참고 · '+x.note:'';$('#openGoogle').href=googleUrl(x.query||x.name+' Tokyo Japan');const marker=markerByName.get(x.name);if(move&&marker&&map){map.setView(marker.getLatLng(),15,{animate:true});marker.openPopup()}if(move&&innerWidth<961) document.querySelector('.map-panel').scrollIntoView({behavior:'smooth',block:'start'})}
function initMap(){if(map||!window.L)return;map=L.map('multiMap',{zoomControl:true,preferCanvas:true}).setView([35.6812,139.7671],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);markerLayer=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),100)}
function cacheKey(x){return 'tokyoGeo:v2:'+String(x.query||x.name)}
function readCache(x){try{const v=JSON.parse(localStorage.getItem(cacheKey(x))||'null');if(v&&Number.isFinite(v.lat)&&Number.isFinite(v.lon))return v}catch(e){}return null}
function saveCache(x,v){try{localStorage.setItem(cacheKey(x),JSON.stringify(v))}catch(e){}}
async function geocode(x){const c=readCache(x);if(c)return c;const q=x.query||`${x.name} ${x.area} Tokyo Japan`;const urls=[`https://photon.komoot.io/api/?q=${encodeURIComponent(q)}&limit=1`,`https://nominatim.openstreetmap.org/search?format=json&limit=1&accept-language=ja,en&q=${encodeURIComponent(q)}`];for(const u of urls){try{const r=await fetch(u,{headers:{'Accept':'application/json'}});if(!r.ok)continue;const j=await r.json();let lat,lon;if(j&&j.features&&j.features[0]){const c=j.features[0].geometry.coordinates;lon=Number(c[0]);lat=Number(c[1])}else if(Array.isArray(j)&&j[0]){lat=Number(j[0].lat);lon=Number(j[0].lon)}if(Number.isFinite(lat)&&Number.isFinite(lon)&&lat>34&&lat<37&&lon>138&&lon<141){const v={lat,lon};saveCache(x,v);return v}}catch(e){}}return null}
function iconFor(x,i){return L.divIcon({className:'leaflet-div-icon',html:`<div class="map-marker ${markerClass(x)}"><span>${i+1}</span></div>`,iconSize:[30,30],iconAnchor:[15,29],popupAnchor:[0,-28]})}
function popupFor(x,i){return `<div class="popup-index">목록 ${i+1}번</div><div class="popup-title">${esc(x.name)}</div><div class="popup-meta">${esc(x.area)}${tab==='spots'&&x.categories?.length?' · '+esc(x.categories[0]):''}</div>`}
async function updateMap(list){initMap();if(!map||!markerLayer)return;const token=++renderToken;markerLayer.clearLayers();markerByName.clear();const loading=$('#mapLoading'),cnt=$('#mapLoadCount');loading.hidden=!list.length;cnt.textContent=`0 / ${list.length}`;let done=0;const points=[];const queue=list.map((x,i)=>({x,i}));const workers=Math.min(6,queue.length);async function worker(){while(queue.length){const item=queue.shift();const pos=await geocode(item.x);if(token!==renderToken)return;done++;cnt.textContent=`${done} / ${list.length}`;if(pos){const marker=L.marker([pos.lat,pos.lon],{icon:iconFor(item.x,item.i),title:`${item.i+1}. ${item.x.name}`}).bindPopup(popupFor(item.x,item.i));marker.on('click',()=>{const btn=[...document.querySelectorAll('.place-card')].find(b=>b.dataset.name===item.x.name);select(item.x,btn,false);if(btn)btn.scrollIntoView({behavior:'smooth',block:'nearest'})});marker.addTo(markerLayer);markerByName.set(item.x.name,marker);points.push([pos.lat,pos.lon])}}}await Promise.all(Array.from({length:workers},worker));if(token!==renderToken)return;loading.hidden=true;if(points.length){if(points.length===1)map.setView(points[0],14);else map.fitBounds(points,{padding:[34,34],maxZoom:14})}else map.setView([35.6812,139.7671],11);setTimeout(()=>map.invalidateSize(),50)}
function switchTab(next){tab=next;area='전체';category='전체';query='';search.value='';document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#listTitle').textContent=titles[tab][0];$('#listSub').textContent=titles[tab][1];$('#pageTitle').textContent=pageCopy[tab][0];$('#pageSub').textContent=pageCopy[tab][1];renderCategoryButtons();renderFilters();renderCards();renderLegend()}
function renderLegend(){let el=document.querySelector('.map-legend');if(!el){el=document.createElement('div');el.className='map-legend';document.querySelector('.map-head>div').appendChild(el)}el.innerHTML=tab==='restaurants'?'<span class="legend-item"><i class="legend-dot food"></i>맛집</span>':'<span class="legend-item"><i class="legend-dot tour"></i>관광</span><span class="legend-item"><i class="legend-dot walk"></i>산책</span><span class="legend-item"><i class="legend-dot view"></i>전망</span><span class="legend-item"><i class="legend-dot shop"></i>쇼핑</span>'}
$('#spotCount').textContent=DATA.spots.length;$('#foodCount').textContent=DATA.restaurants.length;$('#summaryCount').textContent=DATA.spots.length+DATA.restaurants.length;document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));search.oninput=e=>{query=e.target.value;renderCards()};switchTab('spots');
})();
